name: Main workflow

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') &&
      !startsWith(github.event.head_commit.message, 'docs')"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Go environment
        uses: actions/setup-go@v4.1.0

      - name: Install dependencies
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      # TODO: Lint the code too.
      - name: Check the formatting
        run: shfmt --diff *.sh
